/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/brandTheme.ts
 * Command: astryx theme build src/theme/brandTheme.ts --out src/theme/brand.css
 * Generated: 2026-09-23T06:38:40.740Z
 */

/// <reference path="./brand.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const brandTheme: DefinedTheme;
