import { Hono } from "hono";
import { instrumentsRoute } from "./instruments";
import { boardsRoute } from "./boards";
import { watchlistRoute } from "./watchlist";
import { quotesRoute } from "./quotes";
import { klineRoute } from "./kline";
import { featuresRoute } from "./features";
import { signalsRoute } from "./signals";
import { newsRoute } from "./news";
import { backtestsRoute } from "./backtests";
import { threadsRoute } from "./agents/threads";
import { chatRoute } from "./agents/chat";
import { chipsRoute } from "./chips";
import { fundflowRoute } from "./fundflow";
import { heatmapRoute } from "./heatmap";
import { factorsRoute } from "./factors";
import { strategiesRoute } from "./strategies";
import { screensRoute } from "./screens";
import { profileRoute } from "./profile";
import { syncRoute } from "./sync";
import { reviewsRoute } from "./reviews";
import { stockPoolRoute } from "./stock-pool";
// import { adminRoute } from "./admin";

const api = new Hono();
api.route("/instruments", instrumentsRoute);
api.route("/boards", boardsRoute);
api.route("/watchlist", watchlistRoute);
api.route("/kline", klineRoute);
api.route("/backtests", backtestsRoute);
api.route("/chips", chipsRoute);
api.route("/fundflow", fundflowRoute);
api.route("/heatmap", heatmapRoute);
api.route("/factors", factorsRoute);
api.route("/strategies", strategiesRoute);
api.route("/screens", screensRoute);
api.route("/profile", profileRoute);
api.route("/sync", syncRoute);
api.route("/reviews", reviewsRoute);
api.route("/stock-pool", stockPoolRoute);
// api.route("/signals", signalsRoute);
api.route("/news", newsRoute);
// api.route("/backtests", backtestsRoute);
api.route("/agents/threads", threadsRoute);
api.route("/agents/chat", chatRoute);
// api.route("/admin", adminRoute);

export { api };
